#!/bin/bash

# Atualizar lista de pacotes e sistema
echo "Atualizando a lista de pacotes..."
sudo apt update && sudo apt upgrade -y

# Instalar o Apache
echo "Instalando o Apache..."
sudo apt install apache2 -y

# Habilitar o Apache para iniciar automaticamente ao inicializar o sistema
echo "Habilitando o Apache para iniciar automaticamente..."
sudo systemctl enable apache2

# Iniciar o Apache
echo "Iniciando o Apache..."
sudo systemctl start apache2

# Ajustar o Firewall para permitir tráfego HTTP e HTTPS
echo "Configurando o firewall para permitir tráfego HTTP e HTTPS..."
sudo ufw allow 'Apache Full'

# Verificar o status do Apache
echo "Verificando o status do Apache..."
sudo systemctl status apache2

# Imprimir mensagem de conclusão
echo "O servidor web Apache foi provisionado com sucesso!"

# Exibir o endereço IP do servidor
echo "O servidor está rodando no IP:"
hostname -I
